# /etc/modprobe.d/blacklist-ebtables.conf
# Mitigation for CVE-2026-53266: Netfilter ARP table corruption
# Force all module load requests to exit successfully with 0 without loading code into ring-0

install ebtables /bin/true
install ebtable_nat /bin/true
install ebtable_broute /bin/true
install ebtable_filter /bin/true
install ebt_snat /bin/true
install ebt_dnat /bin/true
install ebt_arpreply /bin/true

blacklist ebtables
blacklist ebtable_nat
blacklist ebt_snat
blacklist ebt_arpreply
